### ISSUE TITLE
[Todo] Optimize 2021 Octobr data [GitHub Organization Graphics]

### ISSUE THREAD

**Issue by seanpm2001** [seanpm2001/GitHub_Organization_Info#166]
### Prerequisites

- [X] I verified that this is not an existing issue
- [X] This is not a question, poll, or discussion
- [X] I checked the documentation to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] The repository was downloaded to my device/was viewing through the web browser
- [X] I was using the latest version of the project
- [X] I was using the version from the right source
- [X] I did not modify the project

### My issue involves...

- [ ] An image file (being missing)
- [X] An image file (being in the wrong place)
- [ ] An image file (corrupted)
- [ ] The project language file (won't run)
- [ ] The project language file (doesn't run correctly)
- [ ] Documentation (not being clear)
- [ ] Documentation (being missing)
- [X] Other (please describe)

### I am running the following operating system (choose only one)

- [ ] Android 1.1 (Petit Four)
- [ ] Android 1.5 (Cupcake)
- [ ] Android 1.6 (Donut)
- [ ] Android 2.0 (Eclair)
- [ ] Android 2.1/2.2 (Froyb)
- [ ] Android 2.3 (Gingerbread)
- [ ] Android 3.0 (Honeycomb)
- [ ] Android 4.0 (Ice Cream Sandwich)
- [ ] Android 4.1/4.2/4.3 (JellyBean)
- [ ] Android 4.4 (KitKat)
- [ ] Android 5.0/5.1 (Lollipop)
- [ ] Android 6.0/6.1 (Marshmallow)
- [ ] Android 7.0/7.1 (Nougat)
- [ ] Android 8.0/8.1 (Oreo)
- [ ] Android 9.0/9.1 (Pie)
- [ ] Android 10.0/10.1 (Q)
- [ ] Android 11.0/11.1 (R)
- [ ] Android 12.0/12.1 (S)
- [ ] CentOS 6
- [ ] CentOS 7
- [ ] CentOS 8
- [ ] CentOS 8 (stream)
- [ ] Fedora Linux Core 1
- [ ] Fedora Linux Core 2
- [ ] Fedora Linux Core 3
- [ ] Fedora Linux Core 4
- [ ] Fedora Linux Core 5
- [ ] Fedora Linux Core 6
- [ ] Fedora Linux 7
- [ ] Fedora Linux 8
- [ ] Fedora Linux 9
- [ ] Fedora Linux 10
- [ ] Fedora Linux 11
- [ ] Fedora Linux 12
- [ ] Fedora Linux 13
- [ ] Fedora Linux 14
- [ ] Fedora Linux 15
- [ ] Fedora Linux 16
- [ ] Fedora Linux 17
- [ ] Fedora Linux 18
- [ ] Fedora Linux 19
- [ ] Fedora Linux 20
- [ ] Fedora Linux 21
- [ ] Fedora Linux 22
- [ ] Fedora Linux 23
- [ ] Fedora Linux 24
- [ ] Fedora Linux 25
- [ ] Fedora Linux 26
- [ ] Fedora Linux 27
- [ ] Fedora Linux 28
- [ ] Fedora Linux 29
- [ ] Fedora Linux 30
- [ ] Fedora Linux 31
- [ ] Fedora Linux 32
- [ ] Fedora Linux 33
- [ ] Fedora Linux 34
- [ ] Fedora Linux 35
- [ ] Fedora Linux 36
- [ ] iPhoneOS 1
- [ ] iPhoneOS 2
- [ ] iPhoneOS 3
- [ ] iPadOS 13
- [ ] iPadOS 14
- [ ] iPadOS 15
- [ ] iOS 4
- [ ] iOS 5
- [ ] iOS 6
- [ ] iOS 7
- [ ] iOS 8
- [ ] iOS 9
- [ ] iOS 10
- [ ] iOS 11
- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Apple System 6
- [ ] Mac OS 7
- [ ] Mac OS 8
- [ ] Mac OS 9
- [ ] Mac OS X 10.0 (Cheetah)
- [ ] Mac OS X 10.1 (Puma)
- [ ] Mac OS X 10.2 (Jaguar)
- [ ] Mac OS X 10.3 (Panther)
- [ ] Mac OS X 10.4 (Tiger)
- [ ] Mac OS X 10.5 (Leopard)
- [ ] Mac OS X 10.6 (Snow Leopard)
- [ ] OS X 10.7 (Lion)
- [ ] OS X 10.8 (Mountain Lion)
- [ ] OS X 10.9 (Mavericks)
- [ ] OS X 10.10 (Yosemite)
- [ ] OS X 10.11 (El Capitan)
- [ ] MacOS 10.12 (Sierra)
- [ ] MacOS 10.13 (High Sierra)
- [ ] MacOS 10.14 (Mojave)
- [ ] MacOS 10.15 (Catalina)
- [ ] MacOS 11.x (Big Sur)
- [ ] MacOS 12.x (Monterey)
- [ ] Ubuntu 4.10
- [ ] Ubuntu 5.04
- [ ] Ubuntu 5.10
- [ ] Ubuntu 6.06
- [ ] Ubuntu 6.10
- [ ] Ubuntu 7.04
- [ ] Ubuntu 7.10
- [ ] Ubuntu 8.04
- [ ] Ubuntu 8.10
- [ ] Ubuntu 9.04
- [ ] Ubuntu 9.10
- [ ] Ubuntu 10.04
- [ ] Ubuntu 10.10
- [ ] Ubuntu 11.04
- [ ] Ubuntu 11.10
- [ ] Ubuntu 12.04
- [ ] Ubuntu 12.10
- [ ] Ubuntu 13.04
- [ ] Ubuntu 13.10
- [ ] Ubuntu 14.04
- [ ] Ubuntu 14.10
- [ ] Ubuntu 15.04
- [ ] Ubuntu 15.10
- [ ] Ubuntu 16.04
- [ ] Ubuntu 16.10
- [ ] Ubuntu 17.04
- [ ] Ubuntu 17.10
- [ ] Ubuntu 18.04
- [ ] Ubuntu 18.10
- [ ] Ubuntu 19.04
- [ ] Ubuntu 19.10
- [X] Ubuntu 20.04
- [ ] Ubuntu 20.10
- [ ] Ubuntu 21.04
- [ ] Ubuntu 21.10
- [ ] Ubuntu 22.04
- [ ] Ubuntu 22.10
- [ ] Windows 3.0
- [ ] Windows 3.1
- [ ] Windows NT 3.1
- [ ] Windows NT 3.11
- [ ] Windows NT 3.5
- [ ] Windows NT 3.51
- [ ] Windows NT 4.0
- [ ] Windows 95
- [ ] Windows 98
- [ ] Windows ME
- [ ] Windows 2000
- [ ] Windows XP (no service pack)
- [ ] Windows XP (with service pack 1)
- [ ] Windows XP (with service pack 2)
- [ ] Windows XP (with service pack 3)
- [ ] Windows Vista (no service pack)
- [ ] Windows Vista (with service pack 1)
- [ ] Windows Vista (with service pack 2)
- [ ] Windows 7 (no service pack)
- [ ] Windows 7 (with service pack 1)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 11
- [ ] Windows Server 2003
- [ ] Windows Server 2003 R2
- [ ] Windows Server 2008
- [ ] Windows Server 2008 R2
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Other/unlisted

### I am running the following web browser (choose only one) (please also list the specific version below)

- [ ] AOSP (Android Stock Browser, not to be confused with Google Chrome/Google Chromium)
- [ ] Brave
- [ ] Basilisk
- [ ] Comodo IceDragon
- [ ] Comodo Dragon
- [ ] DuckDuckGo
- [X] Firefox
- [ ] Google Chrome
- [ ] Google Chromium
- [ ] GNU IceCat
- [ ] Internet Explorer
- [ ] Konquerer
- [ ] Lynx
- [ ] Microsoft Edge
- [ ] Netscape
- [ ] Opera
- [ ] Opera Mini
- [ ] Opera GX
- [ ] Pale Moon
- [ ] Safari
- [ ] Samsung Internet
- [ ] SeaMonkey
- [ ] Tor
- [ ] TenFourFox
- [ ] Vivaldi
- [ ] Waterfox
- [ ] Yandex
- [ ] Other/not listed here

### I obtained this repository data from...

- [X] This GitHub repository

### I am running this repository in a virtual machine...

- [ ] Yes (with Oracle VM VirtualBox)
- [ ] Yes (with VMWare)
- [ ] Yes (with Hyper-V)
- [ ] Yes (with Qemu)
- [ ] Yes (with another virtual machine option that isn't listed)
- [X] No (I am running it on my host computer)

### Description

***

The following directories of the parent /OrganizationGraphics/ need to be optimized to match the rest of the project.

- [ ] October 6th
- [ ] October 14th
- [ ] October 18th
- [ ] October 23rd
- [ ] October 25th

***

### Steps to Reproduce

There are no steps needed to reproduce.

### Expected behavior

I didn't expect anything

### Actual behavior

The project is incomplete.

### Git-image repository version

V1.1.58A
